### ISSUE TITLE
compilation、

### ISSUE THREAD

**Issue by ShiwenH** [kzampog/kabamaru#2]

**Comment by ShiwenH** [comment]
Hi. It is me again.

When I tried to compile this project, I got the following information.

when should i do to fix it

CMake Error at CMakeLists.txt:13 (find_package):
  Could not find a configuration file for package "namaris" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    C:/Users/Steven/Desktop/namaris-master/namaris-master/build/namaris-config.cmake, version: 0.1.0 (32bit)

**Comment by kzampog** [comment]
Hi again! :)

You could try `make` and `make install` this library:
https://github.com/aecins/namaris
before building this. I have been using this with the following version of SiftGPU:
https://github.com/kzampog/SiftGPU
which has CUDA enabled and seems to compile with no errors (you will might need to `make` and `make install` this one as well).

I apologize for the horrible CMake file :)
